### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by crazysnailboy** [crazysnailboy/Halloween#1]
#### Bugs
- [ ] witches act like pigmen and gang up on the player when hit
- [ ] when curses are on the player, they make items (e.g. bows) see through/invisible
- [ ] ~jumpkins not correctly aligned when initially spawned or when inactive~

#### Enhancements
- [ ] ~mobs don't spawn in non-vanilla biomes~
- [ ] sounds for treaters
- [ ] make loot table for thank items for mega candy from treaters

##### Fixed in v0.1.10
- [x] jumpkins not spawning (introduced in v0.1.9)

##### Fixed in v0.1.9
- [x] haunters should spawn fake husks in the desert and fake strays if in snowy biomes
- [x] creeper curse destroys blocks and creates ghost blocks when mobGriefing = false
- [x] different sounds for jumpkins
- [x] candy text and/or drops multiply the longer you right-click

##### Fixed in v0.1.8
- [x] husk variants of zombie hands
- [x] haunters changing opacity cause other mobs to also change
- [x] zombie curse causes crash when applied to mobs (introduced in v0.1.6)

##### Fixed in v0.1.7
- [x] haunters make particles when they land
- [x] haunters should be immune to curses
- [x] hallowitches don't drop curse orbs
- [x] treaters should drop a single type of item when thanking for candy
- [x] no reward from treaters for giving them mega candy
- [x] larger spread on candies from creeperween explosions
- [x] jumpkins don't light up correctly when awakened
- [x] jumpkins look at you
- [x] curse text not coloured correctly
- [x] witch treaters should spawn vanilla witches or hallowitches when killed (50/50)
- [x] when creepers from haunters explode, the haunter doesn't always spawn any other mobs

##### Fixed in v0.1.6
- [x] curse heads don't render in 1.11+ (introduced in v0.1.5)
- [x] improved treaters picking up candy (requires mobGriefing = true)
- [x] curses don't vertically align with the player during flight
- [x] treaters when killed by arrows dont turn into their mob
- [x] config option for "legacy mode" - i.e. disable changes in the revival and revert to original behaviour
- [x] slime & zombie curses have legacy & revival modes

##### Fixed in v0.1.5
- [x] config option to disable ambient sounds
- [x] curses work on all living mobs
- [x] ghast curse goes too high above the player
- [x] jumpkin not affected by the ghast curse
- [x] zombie hands can spawn zombies in the ground
- [x] zombie hands don't make nearby zombies bury themselves

##### Fixed in v0.1.4
- [x] zombie and spider curses have broken textures
- [x] zombie hands occasionally go really fast
- [x] creeperweens dont use their secondary face

##### Fixed in v0.1.3
- [x] curses don't work in 1.11+
- [x] curse balls curse you when you use them
- [x] curses stack
- [x] curses jump around vertically when the player moves
- [x] spider curse uses slime sound
- [x] detonating the creeper curse results in "ghost blocks"

##### Fixed in v0.1.2
- [x] pumpkin and grape candies have their names and/or textures switched
- [x] curse orbs use the wrong texture (should be ender pearls)
- [x] right-clicking a witch gives it a curse
- [x] witches dont despawn after hitting a player with a curse orb
- [x] witches move too quickly
- [x] treaters move too quickly
- [x] treaters don't despawn when it becomes daytime
- [x] crash when infected with ghast curse

##### Fixed in v0.1.1
- [x] crash in 1.11+ caused by zombiehands unearthing

#### Possible Ideas
- craftable candy
- change mob spawning rates based on the date
- restore original treater drops under "legacy mode"

**Comment by darthvader45** [comment]
Awesome stuff.  Definitely liking the loot table.
